### ISSUE TITLE
Development roadmap

### ISSUE THREAD

**Issue by codingchili** [codingchili/chili-game-ext#77]
Where we are and where it's going.

**Comment by codingchili** [comment]
Some ideas
- [ ] background compilation of groovy scripts, rely on tests rather than startup compilation.
- [ ] possibilities of deploying an ephemeral instance with players from different realms. (pvp/dungeons etc)
- [ ] quests, achievements, mini-map, world map
- [ ] reduce allocations made on the event-loop in the Grid class for spatial hashing.
- [ ] investigate how the RingBufferScheduler can be used to improve scheduling performance.

**Comment by codingchili** [comment]
More ideas

support for udp
- [ ] split initial spawn message into one event/each. this will avoid fragmentation. (required)
- [ ] split inventory list 
- [ ] split loot event list
- [ ] split class list
- [ ] enable gzip (required)
- [ ] disable pretty json (optional)

Spawn event with full list of (5) entities, 
compact json: original size: 4692 / gzipped size: 969
pretty json: original size: 7545 / gzipped size: 1148

We'll keep tracking changes, no priority on implementing the changes/mode until we are feature complete. Tracking it to make sure it's possible in the future.

**Comment by codingchili** [comment]
Changes that affect mobile usability needs to be tracked as well.
